pkg: monitoring: postinst: really stop the agent
Really stop the agent. First try to be polite with init but in case that
fails read in the PIDFILE and slay it ourselves

diff --git a/pkg/monitoring/debian/postinst b/pkg/monitoring/debian/postinst
--- a/pkg/monitoring/debian/postinst
+++ b/pkg/monitoring/debian/postinst
@@ -3,12 +3,15 @@ update-rc.d rackspace-monitoring-agent defaults 91 09
 
 case "$1" in
     configure)
-         # Restart only if we find a config file in place
+         /etc/init.d/rackspace-monitoring-agent stop || :
+
+         # Cleanup init's mess if it fails to stop
+         PIDFILE=/var/run/rackspace-monitoring-agent.pid
+         start-stop-daemon --stop --retry 5 --quiet --pidfile $PIDFILE --name rackspace-monit --signal KILL
+         echo "stop returned $?"
+
+         # Start only if we find a config file in place
          if [ -f /etc/rackspace-monitoring-agent.cfg ]; then
-              # Try being nice, then try pkilling
-              /etc/init.d/rackspace-monitoring-agent stop || \
-                kill -9 `cat /var/run/rackspace-monitoring-agent.pid` || \
-                pkill -9 -x rackspace-monit || :
               /etc/init.d/rackspace-monitoring-agent start || :
          fi
         ;;
